"""
Forms for User model.
Auto-generated by Flask Scaffold Generator.
"""

from flask_wtf import FlaskForm
from wtforms import (
    StringField, IntegerField, FloatField, BooleanField,
    DateField, DateTimeField, HiddenField, TextAreaField, DecimalField,
    PasswordField, EmailField, URLField, SubmitField
)
from wtforms.validators import DataRequired, Optional, Length, Email, URL, EqualTo

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(1, 64)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    next = HiddenField()
    submit = SubmitField('Log In')

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(1, 64)])
    password = PasswordField('Password', validators=[
        DataRequired(),
        EqualTo('password2', message='Passwords must match.')
    ])
    password2 = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')

class UserForm(FlaskForm):
    """Form for creating/editing User."""
    username = StringField('Username', validators=[DataRequired(), Length(max=64)])
    password_hash = PasswordField('Password Hash', validators=[Optional()])
    submit = SubmitField('Submit')
