"""
Routes for User blueprint.
Auto-generated by Flask Scaffold Generator.
"""

from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user, login_user, logout_user
from extensions import db, login_manager
from models import User
from .forms import UserForm, LoginForm, RegistrationForm

users_bp = Blueprint(
    'users',
    __name__,
    url_prefix='/users',
    template_folder='../templates/users'
)

@users_bp.route('/')
@login_required
def list_users():
    """List all User records."""
    items = User.query.all()
    return render_template(
        'users/list.html',
        items=items,
        model_name='User'
    )

@users_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create_users():
    """Create a new User."""
    form = UserForm()
    if form.validate_on_submit():
        try:
            item = User()
            form.populate_obj(item)
            # No user_fk_field found matching 'users.id'
            db.session.add(item)
            db.session.commit()
            flash('User created successfully!', 'success')
            return redirect(url_for('users.list_users'))
        except Exception as e:
            db.session.rollback()
            flash(f'Error creating User: {str(e)}', 'danger')
    return render_template(
        'users/form.html',
        form=form,
        title='Create User',
        action='create'
    )

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@users_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember.data)
            flash('Logged in successfully.', 'success')
            next_page = form.next.data
            return redirect(next_page or url_for('users.list_users'))
        flash('Invalid username or password.', 'danger')
    return render_template('users/login.html', form=form)

@users_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('users.login'))

@users_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Registration successful. Please log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/register.html', form=form)

@users_bp.route('/<int:id>')
@login_required
def view_users(id):
    """View a single User."""
    item = User.query.get_or_404(id)
    return render_template(
        'users/view.html',
        item=item,
        model_name='User'
    )

@users_bp.route('/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def edit_users(id):
    """Edit an existing User."""
    item = User.query.get_or_404(id)
    form = UserForm(obj=item)
    if form.validate_on_submit():
        try:
            form.populate_obj(item)
            db.session.commit()
            flash('User updated successfully!', 'success')
            return redirect(url_for('users.view_users', id=id))
        except Exception as e:
            db.session.rollback()
            flash(f'Error updating User: {str(e)}', 'danger')
    return render_template(
        'users/form.html',
        form=form,
        title=f'Edit User',
        action='edit',
        item=item
    )

@users_bp.route('/<int:id>/delete', methods=['POST'])
@login_required
def delete_users(id):
    """Delete a User."""
    item = User.query.get_or_404(id)
    try:
        db.session.delete(item)
        db.session.commit()
        flash('User deleted successfully!', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Error deleting User: {str(e)}', 'danger')
    return redirect(url_for('users.list_users'))
